[mongodb]
98.93.193.198
[catlogue]
catlogue.joindevops.shop
[user]
user.joindevops.shop
[cart]
cart.joindevops.shop
[shipping]
shipping.joindevops.shop
[payment]
payment.joindevops.shop
[web]
web.joindevops.shop